# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
30 curated UGC content items with gold labels for brand-safe ad review.

Difficulty distribution: 10 easy, 10 medium, 10 hard.
Gold labels follow IAB Content Taxonomy 3.0 and GARM Brand Safety Floor standards.
"""

from typing import Any, Dict, List

CONTENT_ITEMS: List[Dict[str, Any]] = [
    # =========================================================================
    # EASY (10 items) — clear-cut cases, unambiguous signals
    # =========================================================================
    {
        "content_id": "easy_001",
        "content_text": "Just made the most amazing chocolate chip cookies! 🍪 Recipe in bio. #baking #homemade #foodie",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Clearly safe lifestyle content",
    },
    {
        "content_id": "easy_002",
        "content_text": "Morning run done! 5 miles before sunrise. Nothing beats that feeling 🏃‍♂️ #fitness #running #motivation",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Fitness/wellness content, universally brand-safe",
    },
    {
        "content_id": "easy_003",
        "content_text": "I want to f***ing kill my sister she ate my last slice of pizza 😤😤😤",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_PROFANITY",
        "gold_garm_category": "GARM_OBSCENITY_PROFANITY",
        "gold_risk_level": "HIGH",
        "notes": "Profanity + violent language, clear reject",
    },
    {
        "content_id": "easy_004",
        "content_text": "Buy cheap Xanax no prescription needed!! DM for prices. Discreet shipping worldwide 💊",
        "content_type": "bio",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ILLEGAL",
        "gold_garm_category": "GARM_CRIME_HARMFUL",
        "gold_risk_level": "CRITICAL",
        "notes": "Illegal drug sales, immediate reject",
    },
    {
        "content_id": "easy_005",
        "content_text": "Sunset hike with the crew 🌅 Nature is the best therapy. #hiking #outdoors #adventure",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Outdoor/nature content, universally safe",
    },
    {
        "content_id": "easy_006",
        "content_text": "GRAPHIC: Compilation of the most brutal street fight knockouts 2024 💀 LIKE AND SUBSCRIBE",
        "content_type": "caption",
        "platform": "youtube",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_VIOLENCE",
        "gold_garm_category": "GARM_DEATH_INJURY",
        "gold_risk_level": "HIGH",
        "notes": "Explicit violence, clear reject",
    },
    {
        "content_id": "easy_007",
        "content_text": "My dog learned to high-five today!! 🐾 Took 3 days of training but SO worth it #dogsofinstagram",
        "content_type": "post",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Pet content, universally brand-safe",
    },
    {
        "content_id": "easy_008",
        "content_text": "These [ethnic slur] are ruining our country. Share if you agree. #deportthem",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_HATE_SPEECH",
        "gold_garm_category": "GARM_HATE_SPEECH",
        "gold_risk_level": "CRITICAL",
        "notes": "Explicit hate speech, immediate reject",
    },
    {
        "content_id": "easy_009",
        "content_text": "New study hack: Pomodoro technique changed my life 📚 25 min focus, 5 min break. Try it! #studytok",
        "content_type": "comment",
        "platform": "tiktok",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Educational productivity content",
    },
    {
        "content_id": "easy_010",
        "content_text": "18+ ONLY 🔞 Full uncensored content available. DM me for access. New videos daily 😈",
        "content_type": "bio",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ADULT",
        "gold_garm_category": "GARM_ADULT_EXPLICIT",
        "gold_risk_level": "CRITICAL",
        "notes": "Explicit adult content solicitation",
    },

    # =========================================================================
    # MEDIUM (10 items) — requires contextual judgment
    # =========================================================================
    {
        "content_id": "med_001",
        "content_text": "Honestly the government is lying to us about everything. Wake up sheeple. Do your own research 🐑 #truth",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "notes": "Conspiracy/misinformation framing, brand risk",
    },
    {
        "content_id": "med_002",
        "content_text": "POV: you're at a wine tasting in Tuscany 🍷 This Chianti is absolutely divine. #wine #travel #italy",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Alcohol in aspirational travel context — most brands approve",
    },
    {
        "content_id": "med_003",
        "content_text": "Unpopular opinion: abortion should be illegal in all cases. Fight me in the comments 👇",
        "content_type": "post",
        "platform": "tiktok",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_HATE_SPEECH",
        "gold_risk_level": "HIGH",
        "notes": "Highly divisive political/social topic, brand risk",
    },
    {
        "content_id": "med_004",
        "content_text": "My honest review of the new Call of Duty: the gunplay is insane 🔫 10/10 would recommend #gaming",
        "content_type": "post",
        "platform": "youtube",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Gaming review — fictional violence in mainstream game context is brand-safe",
    },
    {
        "content_id": "med_005",
        "content_text": "Lost 30lbs in 30 days with this ONE weird trick doctors don't want you to know! Link in bio 🔥",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "notes": "Health misinformation / predatory marketing pattern",
    },
    {
        "content_id": "med_006",
        "content_text": "Microdosing psilocybin has genuinely helped my anxiety more than any prescription. Anyone else? 🍄",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_DRUGS",
        "gold_garm_category": "GARM_CRIME_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "notes": "Illegal substance discussion but framed as mental health — escalate for human review",
    },
    {
        "content_id": "med_007",
        "content_text": "This politician is literally destroying democracy. I can't believe people still vote for this clown 🤡",
        "content_type": "comment",
        "platform": "youtube",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "notes": "Political attack content, brand risk regardless of target",
    },
    {
        "content_id": "med_008",
        "content_text": "Vegas baby!! Hit the jackpot at the Bellagio 🎰💰 Best weekend of my life #lasvegas #gambling",
        "content_type": "post",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_GAMBLING",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "notes": "Gambling content — acceptable for some brands, not others. Escalate.",
    },
    {
        "content_id": "med_009",
        "content_text": "Homemade kombucha tutorial! Fermentation is basically controlled bacteria growth 🦠 #health #diy",
        "content_type": "caption",
        "platform": "tiktok",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Health/DIY food content, clearly safe",
    },
    {
        "content_id": "med_010",
        "content_text": "Pirated the new Marvel movie, quality is actually great. DM me for the link 🎬 #movies",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ILLEGAL",
        "gold_garm_category": "GARM_ONLINE_PIRACY",
        "gold_risk_level": "HIGH",
        "notes": "Explicit copyright piracy promotion",
    },

    # =========================================================================
    # HARD (10 items) — subtle, requires deep contextual reasoning
    # =========================================================================
    {
        "content_id": "hard_001",
        "content_text": "As a nurse, I see patients die from gun violence every week. We need common sense reform NOW. #guncontrol",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_DEATH_INJURY",
        "gold_risk_level": "MEDIUM",
        "notes": "Legitimate advocacy but politically divisive — escalate for brand alignment check",
    },
    {
        "content_id": "hard_002",
        "content_text": "My grandfather fought in WWII and always said 'never again.' Seeing what's happening today breaks my heart 💔",
        "content_type": "post",
        "platform": "facebook",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Historical/emotional content without specific political target — safe",
    },
    {
        "content_id": "hard_003",
        "content_text": "Tried that new 'natural' cancer cure everyone's talking about instead of chemo. Week 3 update 🌿",
        "content_type": "post",
        "platform": "youtube",
        "difficulty": "hard",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "CRITICAL",
        "notes": "Dangerous medical misinformation — rejecting chemo for unproven cure",
    },
    {
        "content_id": "hard_004",
        "content_text": "Throwback to my wild college days 😂 Can't believe I survived that era. Grateful for growth #tbt",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Vague reference to past behavior without explicit content — safe",
    },
    {
        "content_id": "hard_005",
        "content_text": "The Proud Boys are the only ones standing up for real Americans. Join us. Link in bio 🇺🇸",
        "content_type": "bio",
        "platform": "twitter",
        "difficulty": "hard",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_HATE_SPEECH",
        "gold_garm_category": "GARM_TERRORISM",
        "gold_risk_level": "CRITICAL",
        "notes": "Designated extremist group recruitment — critical reject",
    },
    {
        "content_id": "hard_006",
        "content_text": "Intermittent fasting day 47. Down 15lbs. Eating window 12pm-8pm. Not for everyone but works for me 💪",
        "content_type": "post",
        "platform": "tiktok",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Personal diet journey — factual, no misinformation, brand-safe",
    },
    {
        "content_id": "hard_007",
        "content_text": "POV: explaining to your parents why you dropped out to trade crypto full time 📈 #crypto #bitcoin",
        "content_type": "caption",
        "platform": "tiktok",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "notes": "Crypto promotion to young audience — financial risk framing, escalate",
    },
    {
        "content_id": "hard_008",
        "content_text": "Satire: Breaking: Local man discovers that working hard actually leads to success. Scientists baffled 🙄",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Clearly labeled satire with no harmful content",
    },
    {
        "content_id": "hard_009",
        "content_text": "My 8-year-old asked me why some kids don't have food. Donated to the local food bank today. Small acts matter 🙏",
        "content_type": "post",
        "platform": "instagram",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "notes": "Charitable/community content — highly brand-safe",
    },
    {
        "content_id": "hard_010",
        "content_text": "Leaked: internal documents show [major brand] knew about safety issues for years. Thread 🧵 1/12",
        "content_type": "post",
        "platform": "twitter",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "HIGH",
        "notes": "Potential defamation/misinformation about a brand — escalate for legal review",
    },
]

# Index by content_id for O(1) lookup
CONTENT_INDEX: Dict[str, Dict[str, Any]] = {
    item["content_id"]: item for item in CONTENT_ITEMS
}
